module.exports = {
  someSidebar: {
    'Get Started': [
      'introduction',
      'register-account',
      'add-website',
      'script-extensions',
      'plausible-script',
      'integration-guides',
      'troubleshoot-integration',
      'landing-page',
      'your-plausible-experience',
    ],
    'Website Settings': [
      'website-settings',
      'change-domain-name',
      'general',
      'visibility',
      'shared-links',
      'embed-dashboard',
      'email-reports',
      'traffic-spikes',
      'slack-reports',
      'reset-site-data',
      'delete-site-data',
      'excluding',
    ],
    'Stats Dashboard': [
      'guided-tour',
      'consolidated-views',
      'compare-stats',
      'filters-segments',
      'google-search-console-integration',
      'realtime-dashboard',
      'top-referrers',
      'top-pages',
      'countries',
      'devices',
      'scroll-depth',
      'subdomain-hostname-filter',
      'metrics-definitions',
      'keyboard-shortcuts',
      'looker-studio',
      'bot-traffic-filtering',
      'dashboard-faq',
      {
        type: 'category',
        label: 'Import & Export',
        items: [
          'google-analytics-import',
          'csv-import',
          'export-stats',
        ],
      },
    ],
    'Goals and Events': [
      'goal-conversions',
      'funnel-analysis',
      'ecommerce-revenue-tracking',
      'outbound-link-click-tracking',
      'file-downloads-tracking',
      'form-submissions-tracking',
      'error-pages-tracking-404',
      'pageview-goals',
      'custom-event-goals',
      {
        type: 'category',
        label: 'Custom properties',
        items: [
          'custom-props/introduction',
          'custom-props/for-pageviews',
          'custom-props/for-custom-events',
          'custom-props/props-dashboard',
        ],
      },
    ],
    'Bypass Adblockers': [
      { type: 'doc', id: 'proxy/introduction', label: 'Overview' },
      {
        type: 'category',
        label: 'Proxy Guides',
        items: [
          { type: 'doc', id: 'proxy/guides/cloudflare', label: 'Cloudflare' },
          { type: 'doc', id: 'proxy/guides/wordpress', label: 'WordPress' },
          { type: 'doc', id: 'proxy/guides/vercel', label: 'Vercel' },
          { type: 'doc', id: 'proxy/guides/netlify', label: 'Netlify' },
          { type: 'doc', id: 'proxy/guides/nginx', label: 'Nginx' },
          { type: 'doc', id: 'proxy/guides/caddy', label: 'Caddy' },
          { type: 'doc', id: 'proxy/guides/apache', label: 'Apache' },
          { type: 'doc', id: 'proxy/guides/laravel', label: 'Laravel' },
        ],
      },
    ],
    'API': [
      'stats-api',
      'stats-api-playground',
      'events-api',
      'sites-api',
    ],
    'Account Settings': [
      '2fa',
      'change-email',
      'login-management',
      'reset-password',
      'dashboard-appearance',
      'delete-account',
    ],
    'Team': [
      'users-roles',
      'agencies-and-freelancers',
      'transfer-ownership',
      {
        type: 'category',
        label: 'Single Sign-On (SSO)',
        items: [
          { type: 'doc', id: 'sso', label: 'Overview' },
          { type: 'doc', id: 'sso-google-workspaces', label: 'Configuring Google Workspaces' },
          { type: 'doc', id: 'sso-ms-entra', label: 'Configuring Microsoft Entra (Azure)' },
          { type: 'doc', id: 'sso-okta', label: 'Configuring Okta' },
        ],
      }
    ],
    'Billing': [
      'trial-to-paid',
      'subscription-plans',
      'change-plan',
      'cancel-subscription',
      'download-invoices',
      'invoice-email',
      'billing',
      'nonprofit-and-education-pricing',
      'compliance',
    ],
  },
}
